/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.devlauten.rxjava;

import io.reactivex.rxjava3.core.Observable;
import io.reactivex.rxjava3.schedulers.Schedulers;

import java.util.Random;

import static java.util.concurrent.TimeUnit.MILLISECONDS;

public class App {
    @Deprecated
    public String getGreeting() {
        return "Hello World!";
    }

    @Deprecated
    public Runnable runnable = () -> System.out.println(getGreeting());

    public Observable<Integer> fakeUserInput() {
        Random random = new Random();
        return Observable.intervalRange(0, 100, 500, 50, MILLISECONDS)

                .concatMap(number -> Observable.just(random.nextInt(20))
                        .delay(random.nextInt(500), MILLISECONDS))
                .map(number -> random.nextInt(20));
    }

    public static void main(String[] args) {
        new RxReader().linesFromInput()
                .observeOn(Schedulers.trampoline())
                .map(Integer::parseInt)
                .concatMapMaybe(x -> RxFibonacci.fibs().elementAt(x))
                .blockingSubscribe(System.out::println);
    }
}
